
[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[general]
import = ["~/.config/alacritty/themes/tokyonight/tokyonight_night.toml"]
